blank_issues_enabled: false
issue_template:
  - bug_report.md
  - feature_request.md
contact_links:
  - name: General Questions
    url: https://github.com/Duc-Developer/axios-token-refresh/discussions
    about: "Have a question or need help? Start a discussion here."